# Generated by Django 2.2.5 on 2019-10-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('servicio', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('image', models.ImageField(default='media/default.png', upload_to='auto_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
